### ISSUE TITLE
No results when '.strings' files are not UTF8 encoded

### ISSUE THREAD

**Issue by adambolcsfoldi** [ijoshsmith/abandoned-strings#1]
Don't know if you've had this problem, but I got no results running `abandoned-strings` on my source. Turned out it was the`contentsOfFile` method failing due to the encoding of the `.strings` files not being UTF8 encoded.
I changed the method thusly to fix it.

```
func contentsOfFile(filePath: String) -> String {
    do {
        let usedEncoding = UnsafeMutablePointer<NSStringEncoding>()
        return try String(contentsOfFile: filePath, usedEncoding: usedEncoding)
    }
    catch { return "" }
}
```

**Comment by ijoshsmith** [comment]
Thanks Adam! I applied your fix.
